version: '3'
services:
  worker-analysis:
    container_name: x721w-analysis
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8886:7776'
    volumes:
      - ../logs/x721w-analysis:/usr/src/app/x721w-analysis/logs
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 300m
